#pragma once

#define WS2812_DI_PIN GP13

#ifdef WS2812_DI_PIN
    #define RGBLIGHT_LED_COUNT  4

    #define RGBLIGHT_HUE_STEP   8
    #define RGBLIGHT_SAT_STEP   8
    #define RGBLIGHT_VAL_STEP   8
    #define RGBLIGHT_LIMIT_VAL  64
    #define RGBLIGHT_SLEEP

    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif
